stages:
  load:
    foreach:
      - wine
    do:
      cmd: poetry run python ./scripts/load.py ${item}
      deps:
      - ./scripts/load.py
  preprocess:
    foreach:
      - wine
    do:
      cmd: poetry run python ./scripts/preprocess.py ${item}
      deps:
        - ./scripts/preprocess.py
      outs:
        - ./data/processed/${item}.csv
